/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedCoasRouteImport } from './routes/_protected/coas'
import { Route as ProtectedSettingsRouteRouteImport } from './routes/_protected/settings/route'
import { Route as ProtectedSettingsNotificationsRouteImport } from './routes/_protected/settings/notifications'
import { Route as ProtectedSettingsFeaturesRouteImport } from './routes/_protected/settings/features'
import { Route as ProtectedSettingsAccessibilitysRouteImport } from './routes/_protected/settings/accessibilitys'
import { Route as ProtectedCoasIdRouteImport } from './routes/_protected/coas_.$id'
import { Route as ProtectedLookupsInvoiceSoldRouteImport } from './routes/_protected/lookups/invoice/sold'
import { Route as ProtectedLookupsInvoicePurchaseRouteImport } from './routes/_protected/lookups/invoice/purchase'
import { Route as ProtectedLookupsInvoicePurchaseIdRouteImport } from './routes/_protected/lookups/invoice/purchase_.$id'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCoasRoute = ProtectedCoasRouteImport.update({
  id: '/coas',
  path: '/coas',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsRouteRoute = ProtectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsNotificationsRoute =
  ProtectedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsFeaturesRoute =
  ProtectedSettingsFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsAccessibilitysRoute =
  ProtectedSettingsAccessibilitysRouteImport.update({
    id: '/accessibilitys',
    path: '/accessibilitys',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedCoasIdRoute = ProtectedCoasIdRouteImport.update({
  id: '/coas_/$id',
  path: '/coas/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLookupsInvoiceSoldRoute =
  ProtectedLookupsInvoiceSoldRouteImport.update({
    id: '/lookups/invoice/sold',
    path: '/lookups/invoice/sold',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLookupsInvoicePurchaseRoute =
  ProtectedLookupsInvoicePurchaseRouteImport.update({
    id: '/lookups/invoice/purchase',
    path: '/lookups/invoice/purchase',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLookupsInvoicePurchaseIdRoute =
  ProtectedLookupsInvoicePurchaseIdRouteImport.update({
    id: '/lookups/invoice/purchase_/$id',
    path: '/lookups/invoice/purchase/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/coas': typeof ProtectedCoasRoute
  '/coas/$id': typeof ProtectedCoasIdRoute
  '/settings/accessibilitys': typeof ProtectedSettingsAccessibilitysRoute
  '/settings/features': typeof ProtectedSettingsFeaturesRoute
  '/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/lookups/invoice/purchase': typeof ProtectedLookupsInvoicePurchaseRoute
  '/lookups/invoice/sold': typeof ProtectedLookupsInvoiceSoldRoute
  '/lookups/invoice/purchase/$id': typeof ProtectedLookupsInvoicePurchaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/coas': typeof ProtectedCoasRoute
  '/coas/$id': typeof ProtectedCoasIdRoute
  '/settings/accessibilitys': typeof ProtectedSettingsAccessibilitysRoute
  '/settings/features': typeof ProtectedSettingsFeaturesRoute
  '/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/lookups/invoice/purchase': typeof ProtectedLookupsInvoicePurchaseRoute
  '/lookups/invoice/sold': typeof ProtectedLookupsInvoiceSoldRoute
  '/lookups/invoice/purchase/$id': typeof ProtectedLookupsInvoicePurchaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/_protected/coas': typeof ProtectedCoasRoute
  '/_protected/coas_/$id': typeof ProtectedCoasIdRoute
  '/_protected/settings/accessibilitys': typeof ProtectedSettingsAccessibilitysRoute
  '/_protected/settings/features': typeof ProtectedSettingsFeaturesRoute
  '/_protected/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/_protected/lookups/invoice/purchase': typeof ProtectedLookupsInvoicePurchaseRoute
  '/_protected/lookups/invoice/sold': typeof ProtectedLookupsInvoiceSoldRoute
  '/_protected/lookups/invoice/purchase_/$id': typeof ProtectedLookupsInvoicePurchaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/coas'
    | '/coas/$id'
    | '/settings/accessibilitys'
    | '/settings/features'
    | '/settings/notifications'
    | '/lookups/invoice/purchase'
    | '/lookups/invoice/sold'
    | '/lookups/invoice/purchase/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/coas'
    | '/coas/$id'
    | '/settings/accessibilitys'
    | '/settings/features'
    | '/settings/notifications'
    | '/lookups/invoice/purchase'
    | '/lookups/invoice/sold'
    | '/lookups/invoice/purchase/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/settings'
    | '/_protected/coas'
    | '/_protected/coas_/$id'
    | '/_protected/settings/accessibilitys'
    | '/_protected/settings/features'
    | '/_protected/settings/notifications'
    | '/_protected/lookups/invoice/purchase'
    | '/_protected/lookups/invoice/sold'
    | '/_protected/lookups/invoice/purchase_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/coas': {
      id: '/_protected/coas'
      path: '/coas'
      fullPath: '/coas'
      preLoaderRoute: typeof ProtectedCoasRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/notifications': {
      id: '/_protected/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof ProtectedSettingsNotificationsRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/features': {
      id: '/_protected/settings/features'
      path: '/features'
      fullPath: '/settings/features'
      preLoaderRoute: typeof ProtectedSettingsFeaturesRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/accessibilitys': {
      id: '/_protected/settings/accessibilitys'
      path: '/accessibilitys'
      fullPath: '/settings/accessibilitys'
      preLoaderRoute: typeof ProtectedSettingsAccessibilitysRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/coas_/$id': {
      id: '/_protected/coas_/$id'
      path: '/coas/$id'
      fullPath: '/coas/$id'
      preLoaderRoute: typeof ProtectedCoasIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/lookups/invoice/sold': {
      id: '/_protected/lookups/invoice/sold'
      path: '/lookups/invoice/sold'
      fullPath: '/lookups/invoice/sold'
      preLoaderRoute: typeof ProtectedLookupsInvoiceSoldRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/lookups/invoice/purchase': {
      id: '/_protected/lookups/invoice/purchase'
      path: '/lookups/invoice/purchase'
      fullPath: '/lookups/invoice/purchase'
      preLoaderRoute: typeof ProtectedLookupsInvoicePurchaseRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/lookups/invoice/purchase_/$id': {
      id: '/_protected/lookups/invoice/purchase_/$id'
      path: '/lookups/invoice/purchase/$id'
      fullPath: '/lookups/invoice/purchase/$id'
      preLoaderRoute: typeof ProtectedLookupsInvoicePurchaseIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedSettingsRouteRouteChildren {
  ProtectedSettingsAccessibilitysRoute: typeof ProtectedSettingsAccessibilitysRoute
  ProtectedSettingsFeaturesRoute: typeof ProtectedSettingsFeaturesRoute
  ProtectedSettingsNotificationsRoute: typeof ProtectedSettingsNotificationsRoute
}

const ProtectedSettingsRouteRouteChildren: ProtectedSettingsRouteRouteChildren =
  {
    ProtectedSettingsAccessibilitysRoute: ProtectedSettingsAccessibilitysRoute,
    ProtectedSettingsFeaturesRoute: ProtectedSettingsFeaturesRoute,
    ProtectedSettingsNotificationsRoute: ProtectedSettingsNotificationsRoute,
  }

const ProtectedSettingsRouteRouteWithChildren =
  ProtectedSettingsRouteRoute._addFileChildren(
    ProtectedSettingsRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedSettingsRouteRoute: typeof ProtectedSettingsRouteRouteWithChildren
  ProtectedCoasRoute: typeof ProtectedCoasRoute
  ProtectedCoasIdRoute: typeof ProtectedCoasIdRoute
  ProtectedLookupsInvoicePurchaseRoute: typeof ProtectedLookupsInvoicePurchaseRoute
  ProtectedLookupsInvoiceSoldRoute: typeof ProtectedLookupsInvoiceSoldRoute
  ProtectedLookupsInvoicePurchaseIdRoute: typeof ProtectedLookupsInvoicePurchaseIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedSettingsRouteRoute: ProtectedSettingsRouteRouteWithChildren,
  ProtectedCoasRoute: ProtectedCoasRoute,
  ProtectedCoasIdRoute: ProtectedCoasIdRoute,
  ProtectedLookupsInvoicePurchaseRoute: ProtectedLookupsInvoicePurchaseRoute,
  ProtectedLookupsInvoiceSoldRoute: ProtectedLookupsInvoiceSoldRoute,
  ProtectedLookupsInvoicePurchaseIdRoute:
    ProtectedLookupsInvoicePurchaseIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
