/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedLookupsInvoiceSoldRouteImport } from './routes/_protected/lookups/invoice/sold'
import { Route as ProtectedLookupsInvoicePurchaseRouteImport } from './routes/_protected/lookups/invoice/purchase'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLookupsInvoiceSoldRoute =
  ProtectedLookupsInvoiceSoldRouteImport.update({
    id: '/lookups/invoice/sold',
    path: '/lookups/invoice/sold',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLookupsInvoicePurchaseRoute =
  ProtectedLookupsInvoicePurchaseRouteImport.update({
    id: '/lookups/invoice/purchase',
    path: '/lookups/invoice/purchase',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lookups/invoice/purchase': typeof ProtectedLookupsInvoicePurchaseRoute
  '/lookups/invoice/sold': typeof ProtectedLookupsInvoiceSoldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lookups/invoice/purchase': typeof ProtectedLookupsInvoicePurchaseRoute
  '/lookups/invoice/sold': typeof ProtectedLookupsInvoiceSoldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/lookups/invoice/purchase': typeof ProtectedLookupsInvoicePurchaseRoute
  '/_protected/lookups/invoice/sold': typeof ProtectedLookupsInvoiceSoldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lookups/invoice/purchase' | '/lookups/invoice/sold'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lookups/invoice/purchase' | '/lookups/invoice/sold'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/lookups/invoice/purchase'
    | '/_protected/lookups/invoice/sold'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/lookups/invoice/sold': {
      id: '/_protected/lookups/invoice/sold'
      path: '/lookups/invoice/sold'
      fullPath: '/lookups/invoice/sold'
      preLoaderRoute: typeof ProtectedLookupsInvoiceSoldRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/lookups/invoice/purchase': {
      id: '/_protected/lookups/invoice/purchase'
      path: '/lookups/invoice/purchase'
      fullPath: '/lookups/invoice/purchase'
      preLoaderRoute: typeof ProtectedLookupsInvoicePurchaseRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedLookupsInvoicePurchaseRoute: typeof ProtectedLookupsInvoicePurchaseRoute
  ProtectedLookupsInvoiceSoldRoute: typeof ProtectedLookupsInvoiceSoldRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedLookupsInvoicePurchaseRoute: ProtectedLookupsInvoicePurchaseRoute,
  ProtectedLookupsInvoiceSoldRoute: ProtectedLookupsInvoiceSoldRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
