/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedCoasRouteImport } from './routes/_protected/coas'
import { Route as ProtectedCoasIdRouteImport } from './routes/_protected/coas_.$id'
import { Route as ProtectedLookupsInvoiceSoldRouteImport } from './routes/_protected/lookups/invoice/sold'
import { Route as ProtectedLookupsInvoicePurchaseRouteImport } from './routes/_protected/lookups/invoice/purchase'
import { Route as ProtectedLookupsInvoicePurchaseIdRouteImport } from './routes/_protected/lookups/invoice/purchase_.$id'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCoasRoute = ProtectedCoasRouteImport.update({
  id: '/coas',
  path: '/coas',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCoasIdRoute = ProtectedCoasIdRouteImport.update({
  id: '/coas_/$id',
  path: '/coas/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLookupsInvoiceSoldRoute =
  ProtectedLookupsInvoiceSoldRouteImport.update({
    id: '/lookups/invoice/sold',
    path: '/lookups/invoice/sold',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLookupsInvoicePurchaseRoute =
  ProtectedLookupsInvoicePurchaseRouteImport.update({
    id: '/lookups/invoice/purchase',
    path: '/lookups/invoice/purchase',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLookupsInvoicePurchaseIdRoute =
  ProtectedLookupsInvoicePurchaseIdRouteImport.update({
    id: '/lookups/invoice/purchase_/$id',
    path: '/lookups/invoice/purchase/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coas': typeof ProtectedCoasRoute
  '/coas/$id': typeof ProtectedCoasIdRoute
  '/lookups/invoice/purchase': typeof ProtectedLookupsInvoicePurchaseRoute
  '/lookups/invoice/sold': typeof ProtectedLookupsInvoiceSoldRoute
  '/lookups/invoice/purchase/$id': typeof ProtectedLookupsInvoicePurchaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coas': typeof ProtectedCoasRoute
  '/coas/$id': typeof ProtectedCoasIdRoute
  '/lookups/invoice/purchase': typeof ProtectedLookupsInvoicePurchaseRoute
  '/lookups/invoice/sold': typeof ProtectedLookupsInvoiceSoldRoute
  '/lookups/invoice/purchase/$id': typeof ProtectedLookupsInvoicePurchaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/coas': typeof ProtectedCoasRoute
  '/_protected/coas_/$id': typeof ProtectedCoasIdRoute
  '/_protected/lookups/invoice/purchase': typeof ProtectedLookupsInvoicePurchaseRoute
  '/_protected/lookups/invoice/sold': typeof ProtectedLookupsInvoiceSoldRoute
  '/_protected/lookups/invoice/purchase_/$id': typeof ProtectedLookupsInvoicePurchaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coas'
    | '/coas/$id'
    | '/lookups/invoice/purchase'
    | '/lookups/invoice/sold'
    | '/lookups/invoice/purchase/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coas'
    | '/coas/$id'
    | '/lookups/invoice/purchase'
    | '/lookups/invoice/sold'
    | '/lookups/invoice/purchase/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/coas'
    | '/_protected/coas_/$id'
    | '/_protected/lookups/invoice/purchase'
    | '/_protected/lookups/invoice/sold'
    | '/_protected/lookups/invoice/purchase_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/coas': {
      id: '/_protected/coas'
      path: '/coas'
      fullPath: '/coas'
      preLoaderRoute: typeof ProtectedCoasRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/coas_/$id': {
      id: '/_protected/coas_/$id'
      path: '/coas/$id'
      fullPath: '/coas/$id'
      preLoaderRoute: typeof ProtectedCoasIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/lookups/invoice/sold': {
      id: '/_protected/lookups/invoice/sold'
      path: '/lookups/invoice/sold'
      fullPath: '/lookups/invoice/sold'
      preLoaderRoute: typeof ProtectedLookupsInvoiceSoldRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/lookups/invoice/purchase': {
      id: '/_protected/lookups/invoice/purchase'
      path: '/lookups/invoice/purchase'
      fullPath: '/lookups/invoice/purchase'
      preLoaderRoute: typeof ProtectedLookupsInvoicePurchaseRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/lookups/invoice/purchase_/$id': {
      id: '/_protected/lookups/invoice/purchase_/$id'
      path: '/lookups/invoice/purchase/$id'
      fullPath: '/lookups/invoice/purchase/$id'
      preLoaderRoute: typeof ProtectedLookupsInvoicePurchaseIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedCoasRoute: typeof ProtectedCoasRoute
  ProtectedCoasIdRoute: typeof ProtectedCoasIdRoute
  ProtectedLookupsInvoicePurchaseRoute: typeof ProtectedLookupsInvoicePurchaseRoute
  ProtectedLookupsInvoiceSoldRoute: typeof ProtectedLookupsInvoiceSoldRoute
  ProtectedLookupsInvoicePurchaseIdRoute: typeof ProtectedLookupsInvoicePurchaseIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCoasRoute: ProtectedCoasRoute,
  ProtectedCoasIdRoute: ProtectedCoasIdRoute,
  ProtectedLookupsInvoicePurchaseRoute: ProtectedLookupsInvoicePurchaseRoute,
  ProtectedLookupsInvoiceSoldRoute: ProtectedLookupsInvoiceSoldRoute,
  ProtectedLookupsInvoicePurchaseIdRoute:
    ProtectedLookupsInvoicePurchaseIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
